
[Cage]
	#This is the modifier for how fast entities spin when displayed inside the Cage.
	#Range: 1.0 ~ 20.0
	cageEntitySpinMod = 3.0

[Wallpaper]
	#Set this to determine how much the wallpaper will stick off of the wall.
	#Range: 0.1 ~ 5.0
	widthWallpaper = 1.0

