
[Common]
	#Set this to the chance that a rune will genarate inside a structure.
	#Range: 0.0 ~ 1.0
	runeChance = 0.15

[Structures]
	#This value determines how many extra pieces to a water dome are added.
	#Range: 0 ~ 100
	waterDomePieceMod = 8

[Spires]
	#Set this to the radius you would like for the spires.
	#Range: 0 ~ 100
	spireRadius = 7
	#Set this to the height you would like for spires.
	#Range: 0 ~ 100
	spireHeight = 40
	#Set this to the chance for a death spire to generate.
	#Range: 0.0 ~ 1.0
	deathSpireChance = 0.001

