
[types]

	[types.leaves_type]

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

	[types.wood_type]

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.cfm]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			table = true
			coffee_table = true
			park_bench = true
			stripped_kitchen_counter = true
			stripped_bedside_cabinet = true
			desk_cabinet = true
			upgraded_fence = true
			kitchen_counter = true
			upgraded_gate = true
			stripped_park_bench = true
			cabinet = true
			mail_box = true
			crate = true
			chair = true
			stripped_mail_box = true
			stripped_blinds = true
			bedside_cabinet = true
			stripped_cabinet = true
			kitchen_drawer = true
			desk = true
			stripped_kitchen_drawer = true
			kitchen_sink_dark = true
			stripped_desk_cabinet = true
			stripped_table = true
			blinds = true
			stripped_chair = true
			stripped_kitchen_sink_dark = true
			stripped_desk = true
			kitchen_sink_light = true
			stripped_coffee_table = true
			stripped_crate = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			glass_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			classic_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			mystic_trapdoor = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			beach_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			cottage_door = true
			western_door = true
			paper_door = true
			swamp_door = true
			glass_door = true
			barn_door = true
			mystic_door = true
			bark_glass_door = true
			classic_door = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true

		[entries.wood_type.create]
			window_pane = true
			window = true

